[terminal]
# The VT to run the greeter on. Can be "next", "current" or a number
# designating the VT.
vt = 7

# The default session, also known as the greeter.
[default_session]

# `agreety` is the bundled agetty/login-lookalike. You can replace `/bin/sh`
# with whatever you want started, such as `sway`.
#command = "/usr/sbin/agreety --cmd Hyprland"
command = "tuigreet --cmd hyprland --remember --power-shutdown 'sudo /sbin/poweroff' --power-reboot 'sudo /sbin/shutdown -r now'"
# shutdown -r now; systemctl reboot


# if using wlgreet
#command = "sway --config /etc/greetd/sway-config"

# The user to run the command as. The privileges this user must have depends
# on the greeter. A graphical greeter may for example require the user to be
# in the `video` group.
user = "_greetd"
#user = "greeter"
